### ISSUE TITLE
[Feature Request] ARM binaries

### ISSUE THREAD

**Issue by chromer030** [agourlay/dlm#13]
Please provide native ARM binaries for Linux, macOS, Windows.
ARM is spreading this days : `Apple Silicon` , `SBCs like Raspberry PI` , `Windows on arm SOCs`

**Comment by agourlay** [comment]
I am currently dependent on [upload0rust-binary-action](https://github.com/taiki-e/upload-rust-binary-action) to add more targets.

**Comment by agourlay** [comment]
Looks like it should be possible to publish for more targets
https://github.com/taiki-e/upload-rust-binary-action/blob/main/main.sh#L40

Maybe something like:

```yaml
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: arm-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - x86_64-pc-windows-msvc
            os: windows-latest
```

Have not tried it yet, just capturing some info.
